export const filterOptions = {
  locations: [
    "Alingsås",
    "Arvika",
    "Avesta",
    "Borås",
    "Botkyrka",
    "Eskilstuna",
    "Enköping",
    "Eslöv",
    "Falun",
    "Gävle",
    "Göteborg",
    "Halmstad",
    "Haninge",
    "Helsingborg",
    "Hudiksvall",
    "Huddinge",
    "Hässleholm",
    "Jönköping",
    "Kalmar",
    "Karlshamn",
    "Karlskrona",
    "Karlstad",
    "Kiruna",
    "Kramfors",
    "Kristianstad",
    "Kristinehamn",
    "Kungsbacka",
    "Kungälv",
    "Landskrona",
    "Lidköping",
    "Lidingö",
    "Linköping",
    "Luleå",
    "Lund",
    "Malmö",
    "Mariestad",
    "Motala",
    "Nacka",
    "Norrfjärden",
    "Norrköping",
    "Norrtälje",
    "Nybro",
    "Nyköping",
    "Nynäshamn",
    "Oskarshamn",
    "Piteå",
    "Sala",
    "Sandviken",
    "Sigtuna",
    "Skellefteå",
    "Skövde",
    "Sollentuna",
    "Solna",
    "Stockholm",
    "Sundsvall",
    "Södertälje",
    "Täby",
    "Trelleborg",
    "Trollhättan",
    "Tyresö",
    "Uddevalla",
    "Umeå",
    "Upplands Väsby",
    "Uppsala",
    "Varberg",
    "Västerås",
    "Växjö",
    "Ystad",
    "Örebro",
    "Östersund",
  ],
  activityTypes: [
    "Barnvänligt",
    "Evenemang",
    "Historia & Sevärdheter",
    "Hundvänligt",
    "Kultur",
    "Mat & Dryck",
    "Museum",
    "Natur",
    "Nöje & Underhållning",
    "Shopping",
    "Wellness & Avkoppling",
    "Äventyr & Friluftsliv",
  ],
  timeFrames: ["Heldag", "Halvdag (förmiddag)", "Halvdag (eftermiddag)"],
};

export const activityTypeMapping: Record<string, string[]> = {
  Barnvänligt: [
    "lekland",
    "djurpark",
    "nöjespark",
    "bad",
    "inomhuslek",
    "familjeaktivitet",
    "barnteater",
  ],
  Evenemang: [
    "mässa",
    "marknad",
    "festival",
    "konferens",
    "utställning",
    "konsert",
  ],
  "Historia & Sevärdheter": [
    "slott",
    "kyrka",
    "ruin",
    "monument",
    "historisk plats",
    "arkitektur",
  ],
  Hundvänligt: [
    "hundpark",
    "hundbad",
    "hundvänlig restaurang",
    "hundvänligt café",
    "promenadstig",
    "hundklubb",
  ],
  Kultur: [
    "museum",
    "teater",
    "bibliotek",
    "konst",
    "opera",
    "konsert",
    "utställning",
    "film",
  ],
  "Mat & Dryck": [
    "restaurang",
    "cafe",
    "bageri",
    "bar",
    "pub",
    "streetfood",
    "fine dining",
    "matmarknad",
  ],
  Museum: ["museum", "utställning", "konsthall", "historiskt museum"],
  Natur: [
    "park",
    "natur",
    "reservat",
    "promenad",
    "skog",
    "vandring",
    "strand",
    "fågelskådning",
  ],
  "Nöje & Underhållning": [
    "bio",
    "konsert",
    "klubb",
    "karaoke",
    "spelhall",
    "festival",
    "standup",
  ],
  Shopping: [
    "shopping",
    "galleria",
    "kläder",
    "butik",
    "marknad",
    "design",
    "inredning",
    "second hand",
  ],
  "Wellness & Avkoppling": [
    "spa",
    "massage",
    "yoga",
    "meditation",
    "bad",
    "wellness",
    "hälsa",
  ],
  "Äventyr & Friluftsliv": [
    "klättring",
    "kajak",
    "kanot",
    "skidåkning",
    "snowboard",
    "cykling",
    "äventyrspark",
  ],
};

export const hotelTypes = [
  "lodging",
  "hotel",
  "motel",
  "hostel",
  "guest_house",
  "campground",
];

export type TimeFrame =
  | "Heldag"
  | "Halvdag (förmiddag)"
  | "Halvdag (eftermiddag)";

export const timeFrames: Record<
  TimeFrame,
  { time: string; type: "food" | "activity" }[]
> = {
  Heldag: [
    { time: "10:00", type: "activity" },
    { time: "13:00", type: "food" },
    { time: "15:00", type: "activity" },
  ],
  "Halvdag (förmiddag)": [
    { time: "10:00", type: "activity" },
    { time: "12:00", type: "food" },
  ],
  "Halvdag (eftermiddag)": [
    { time: "14:00", type: "activity" },
    { time: "17:00", type: "food" },
  ],
};
